//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DrawFlowChart.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DRAWFLTYPE                  129
#define IDR_TOOLBAR_GRAPHICS            136
#define IDB_TEXTURE_BITMAP              138
#define ID_RECTANGLE                    32771
#define ID_ELLIPSE                      32772
#define ID_DIAMOND                      32773
#define ID_PARALLELOGRAM                32774
#define ID_GENERICLINE                  32775
#define ID_ARROW_LINE                   32776
#define ID_BROKEN_LINE                  32777
#define ID_START                        32778
#define ID_END                          32779
#define ID_SAVEIMAGE                    32780
#define ID_SAVE_BMP                     32781
#define ID_SEARCH_PATH                  32782
#define ID_MARK_PATH                    32783
#define ID_STOP_MARK                    32784
#define ID_TOOLBAR_START                32785
#define ID_TOOLBAR_DIAMOND              32787
#define ID_TOOLBAR_PARALLELOGRAM        32788
#define ID_TOOLBAR_END                  32789
#define ID_TOOLBAR_SEARCH               32792
#define ID_TOOLBAR_NEXT                 32794
#define ID_TOOLBAR_BROKEN_LINE          32795
#define ID_TOOLBAR_STOP                 32796
#define ID_TOOLBAR_RECTANGLE            32797
#define ID_TOOLBAR_ELLIPSE              32801
#define ID_TOOLBAR_GENERICLINE          32807
#define ID_TOOLBAR_ARROW_LINE           32808
#define ID_TOOLBAR_POLYGONAL_LINE       32810
#define ID_TOOLBAR_ROUNDHEAD_RECTANGLE  32811
#define ID_TOOLBAR_CUSTOM_ROUNDRECTANGLE 32813
#define ID_TOOLBAR_HEXAGON              32815
#define ID_TOOLBAR_ROUNDRECTANGLE       32816
#define ID_TOOLBAR_DOCUMENT             32817
#define ID_TOOLBAR_LADDER               32818
#define ID_TOOLBAR_CYLINDER             32824
#define ID_TOOLBAR_BEZIERLINE           32832
#define ID_TOOLBAR_ARC_LINE             32833
#define ID_VIEW_SELECT_BORDER           32835
#define ID_TOOLBAR_CUSTOM_BEZIERLINE    32839
#define ID_TOOLBAR_CUBIC_SPLINELINE     32840
#define ID_TOOLBAR_QUADRATIC_SPLINELINE 32841
#define ID_EDIT_SMOOTH_BEZIERLINE       32842
#define ID_TOOLBAR_CUBIC_BOX            32845
#define ID_TOOLBAR_MESH_SPHERE          32847
#define ID_TOOLBAR_DDA_LINES            32848
#define ID_TOOLBAR_BRESENHAM_DDALINE    32849
#define ID_TOOLBAR_MIDDLE_CIRCLE        32850
#define ID_TOOLBAR_WU_ANTILINE          32851
#define ID_TOOLBAR_FLATCOLOR_TRIANGLE   32853
#define ID_TOOLBAR_SMOOTHCOLOR_TRIANGLE 32854
#define ID_TOOLBAR_EDGETABLE_FILL_POLYGON 32855
#define ID_TOOLBAR_EDGE_FILL_POLYGON    32856
#define ID_TOOLBAR_FENCE_FILL_POLYGON   32857
#define ID_TOOLBAR_SCANLINE_FILL_POLYGON 32859
#define ID_TOOLBAR_ROTATE_PENTAGRAM     32861
#define ID_TOOLBAR_COHENSUTHERLAND_CLIP_LINE 32862
#define ID_TOOLBAR_MIDPOINT_DIVID_LINE  32863
#define ID_TOOLBAR_LIANGBARSKY_CLIP_LINE 32864
#define ID_TOOLBAR_ARBITRARY_ROTATE_CUBE 32865
#define ID_TOOLBAR_ORTHOGONAL_ROTATE_CUBE 32866
#define ID_TOOLBAR_CABINET_ROTATE_CUBE  32867
#define ID_TOOLBAR_PERSPECTIVE_ROTATE_CUBE 32868
#define ID_TOOLBAR_CUBIC_BEZIER_CURVE   32871
#define ID_TOOLBAR_BICUBIC_BEZIER_PATCH_GRAPH 32872
#define ID_TOOLBAR_BICUBIC_BEZIER_SPHERE_GRAPH 32873
#define ID_TOOLBAR_RATIONAL_QUADRATIC_BEZIER_CIRCLE_GRAPH 32875
#define ID_TOOLBAR_RATIONALQUADRATIC_BEZIER_SPHERE_GRAPH 32876
#define ID_TOOLBAR_BACKFACE_CULL_ROTATE_CUBE 32879
#define ID_TOOLBAR_THREE_CROSS_ROTATE_CUBE 32881
#define ID_TOOLBAR_SPATIAL_ARRANGED_CUBE 32882
#define ID_TOOLBAR_GOURAUD_BICUBIC_BEZIER_SPHERE_GRAPH 32883
#define ID_TOOLBAR_GOURAUD_BIQUATRIC_BEZIER_SPHERE_GRAPH 32884
#define ID_TOOLBAR_PHONG_BIQUATRIC_BEZIER_SPHERE_GRAPH 32885
#define ID_TOOLBAR_TEXTURE_CUBE_GRAPH   32886
#define ID_TOOLBAR_TEXTURE_SPHERE_GRAPH 32887

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32888
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
